include ../make.inc

LIBNAME = lib62_wvl_defs.a

SRC = \
interfaces_62_wvl_wfs.F90  wvl_nl_gradient.F90  wvl_rwwf.F90 \
wvl_hpsitopsi.F90          wvl_psitohpsi.F90    wvl_tail_corrections.F90


include ../make.inc.post


interfaces_62_wvl_wfs.o : interfaces_62_wvl_wfs.F90 
wvl_hpsitopsi.o : wvl_hpsitopsi.F90 
wvl_nl_gradient.o : wvl_nl_gradient.F90 
wvl_psitohpsi.o : wvl_psitohpsi.F90 
wvl_rwwf.o : wvl_rwwf.F90 
wvl_tail_corrections.o : wvl_tail_corrections.F90 
