include ../make.inc

LIBNAME = lib56_recipspace.a

SRC = \
interfaces_56_recipspace.F90 \
cg_rotate.F90       get_kpt_fullbz.F90            irrzg.F90      m_ab7_kpoints.F90  m_kpts.F90     setsym.F90 \
getcut.F90          getmpw.F90                    kpgio.F90      m_bz_mesh.F90      m_nesting.F90  smpbz.F90 \
get_full_kgrid.F90  getph.F90                     kpgstr.F90     m_double_grid.F90 \
m_gsphere.F90 \
m_skw.F90      symg.F90 \
getkgrid.F90        initylmg.F90                  laplacian.F90  ph1d3d.F90     symkchk.F90 \
getkpgnorm.F90  listkk.F90     mkkin.F90          setmqgrid.F90  testkgrid.F90

include ../make.inc.post

