include ../make.inc

LIBNAME = lib20_datashare.a

SRC = \
interfaces_20_datashare.F90  vdw_dftd3_data.F90

include ../make.inc.post

interfaces_20_datashare.o : interfaces_20_datashare.F90 
vdw_dftd3_data.o : vdw_dftd3_data.F90 
