include ../make.inc

LIBNAME = lib02_clib.a

SRC = \
interfaces_02_clib.F90  m_clib.F90

C_SRC = \
align.c           cclock.c  fsi_posix.c  intrinsics.c  md5.c           xexit.c \
calling_levmar.c  etime.c   gnu_tools.c  mallinfo.c    progress_bar.c  xmalloc.c

include ../make.inc.post

