include ../make.inc

LIBNAME = lib53_ffts.a

SRC = \
interfaces_53_ffts.F90 \
m_fft.F90 \
ccfft.F90  fftpac.F90  fourdp_6d.F90  fourdp.F90  fourwf.F90  kgindex.F90  zerosym.F90

include ../make.inc.post

