include ../make.inc

LIBNAME = lib42_nlstrain.a

SRC = \
contistr01.F90  contistr12.F90  contstr23.F90   contstr25.F90  interfaces_42_nlstrain.F90 \
contistr03.F90  contstr21.F90   contstr25a.F90  contstr26.F90


include ../make.inc.post


contistr01.o : contistr01.F90 
contistr03.o : contistr03.F90 
contistr12.o : contistr12.F90 
contstr21.o : contstr21.F90 
contstr23.o : contstr23.F90 
contstr25a.o : contstr25a.F90 
contstr25.o : contstr25.F90 
contstr26.o : contstr26.F90 
interfaces_42_nlstrain.o : interfaces_42_nlstrain.F90 
