include ../make.inc

LIBNAME = lib32_util.a

SRC = \
m_matrix.F90 \
acrossb.F90          hermit.F90              m_atomdata.F90      m_optic_tools.F90      rotmat.F90 \
appdig.F90           interfaces_32_util.F90  matr3eigval.F90     m_pptools.F90          sbf8.F90 \
blow_pawuj.F90       inupper.F90             matr3inv.F90        m_special_funcs.F90    smatrix.F90 \
create_mlms2jmj.F90  isfile.F90              matrginv.F90        m_wfutils.F90          status.F90 \
create_slm2ylm.F90   kramerskronig.F90       m_exp_mat.F90       overlap_g.F90          test_radsintr.F90 \
ctrap.F90            littlegroup_q.F90       m_gwls_utility.F90  proc_distrb_cycle.F90 \
fappnd.F90           mati3det.F90            mknormpath.F90      radsintr.F90 \
findmin.F90          mati3inv.F90        radsmear.F90

include ../make.inc.post

