include ../make.inc

LIBNAME = lib51_manage_mpi.a

SRC = \
interfaces_51_manage_mpi.F90 \
distrb2.F90        initmpi_atom.F90  initmpi_pert.F90              m_io_redirect.F90    pspheads_comm.F90 \
distrb2_hf.F90     initmpi_band.F90 \
m_mpinfo.F90 \
initmpi_seq.F90 \
get_npert_rbz.F90  initmpi_grid.F90  initmpi_world.F90             m_wffile.F90 \
herald.F90         initmpi_img.F90   m_xredistribute.F90


include ../make.inc.post



