include ../make.inc

LIBNAME = lib53_spacepar.a

SRC = \
dotprod_vn.F90  interfaces_53_spacepar.F90  meanvalue_g.F90  multipoles_fftr.F90


include ../make.inc.post


dotprod_vn.o : dotprod_vn.F90 
interfaces_53_spacepar.o : interfaces_53_spacepar.F90 
meanvalue_g.o : meanvalue_g.F90 
multipoles_fftr.o : multipoles_fftr.F90 
