include ../make.inc

LIBNAME = lib10_dumpinfo.a

SRC = \
interfaces_10_dumpinfo.F90  m_build_info.F90  m_cppopts_dumper.F90  m_optim_dumper.F90


include ../make.inc.post


interfaces_10_dumpinfo.o : interfaces_10_dumpinfo.F90 
m_build_info.o : m_build_info.F90 
m_cppopts_dumper.o : m_cppopts_dumper.F90 
m_optim_dumper.o : m_optim_dumper.F90 
