include ../make.inc

LIBNAME = lib59_ionetcdf.a

SRC = \
interfaces_59_ionetcdf.F90  m_crystal_io.F90  m_dfpt_io.F90 \
write_eig.F90  wrt_moldyn_netcdf.F90


include ../make.inc.post


interfaces_59_ionetcdf.o : interfaces_59_ionetcdf.F90 
m_crystal_io.o : m_crystal_io.F90 
m_dfpt_io.o : m_dfpt_io.F90 
write_eig.o : write_eig.F90 
wrt_moldyn_netcdf.o : wrt_moldyn_netcdf.F90 
