include ../make.inc

LIBNAME = lib54_abiutil.a

SRC = \
calcdensph.F90     interfaces_54_abiutil.F90  m_dtset.F90     m_results_out.F90  printmagvtk.F90 \
find_getdtset.F90  m_dens.F90                 mkfilename.F90  m_scf_history.F90


include ../make.inc.post

