include ../make.inc

LIBNAME = lib44_abitypes.a

SRC = \
m_distribfft.F90 \
defs_abitypes.F90  m_args_gs.F90 m_efield.F90  m_energies.F90 \
m_results_gs.F90 \
m_results_img.F90 \
interfaces_44_abitypes_defs.F90  m_efmas_defs.F90  m_results_respfn.F90

include ../make.inc.post

