include ../make.inc

LIBNAME = lib78_eph.a

SRC = \
interfaces_78_eph.F90  m_gkk.F90  m_phgamma.F90  m_phpi.F90  m_sigmaph.F90


include ../make.inc.post


interfaces_78_eph.o : interfaces_78_eph.F90 
m_gkk.o : m_gkk.F90 
m_phgamma.o : m_phgamma.F90 
m_phpi.o : m_phpi.F90 
m_sigmaph.o : m_sigmaph.F90 
