include ../make.inc

LIBNAME = lib52_ffr_mpi_noabirule.a

SRC = \
interfaces_52_fft_mpi_noabirule.F90 \
m_fftcore.F90  \
m_fft_mesh.F90 \
m_fftw3.F90 m_sgfft.F90 \
m_dfti.F90  m_sg2002.F90 \
bound.F90  indirect_parallel_Fourier.F90  sphereboundary.F90 \
getng.F90

include ../make.inc.post

